image: huazhouwang/android-26

before_script:
  - chmod +x ./gradlew

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./gradlew testDebug
  artifacts:
    paths:
    - app/build/reports

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/